### PR TITLE
Fixes for test failures due to PR #219

### PR DESCRIPTION
**Pull request by umarmughal824**
Circle ci fix PR for this https://github.com/open-craft/problem-builder/pull/219.

### CODE REVIEW

**Comment by umarmughal824** [comment]
@xitij2000 @giovannicimolin please run CircleCI test on it. thanks

**Comment by giovannicimolin** [comment]
@umarmughal824 I'm waiting for the CI tests to finish before merging

**Comment by giovannicimolin** [comment]
@umarmughal824 All the tests failed again (https://circleci.com/gh/open-craft/problem-builder/732) apparently, because of this i18nservice:

`TypeError: render_template() got an unexpected keyword argument 'i18n_service'`

This tests are failed on my local environment too, running `run_tests.py`. Please check your dependencies and environment.

**Comment by umarmughal824** [comment]
@giovannicimolin I have seen my code. I have already fixed this. Can you please recheck it or can see the code because we don't have more than **1126** lines in **mentoring.py** but its referencing **1148th** line.

**Comment by umarmughal824** [comment]
@giovannicimolin please make sure you have pulled this code before running those test. Before the things you are refering was same in the previous tests ran by you. But it has been fixed in this code.

**Comment by umarmughal824** [comment]
@giovannicimolin I have seen that you share the previous / old CircleCI tests. Please pull the latest code and run the CircleCI tests and see the shared links in this and the previous PR you have shared the same link again.

**Comment by umarmughal824** [comment]
@giovannicimolin Can you please try it once more? 

Can I test it locally on my system? Is that possible?

**Comment by umarmughal824** [comment]
@xitij2000 @giovannicimolin See the CircleCI tests and it show this error.

```TypeError: render_django_template() got an unexpected keyword argument 'i18n_service'```

But if you see the code of this function. It is expecting this as an keyword argument.
https://github.com/edx/xblock-utils/blob/master/xblockutils/resources.py#L50

See the above link it has following parameter.
```def render_django_template(self, template_path, context=None, i18n_service=None):```

**Comment by giovannicimolin** [comment]
@umarmughal824 The issue here is that you are using a version of XBlock utils that doesn't have the ` i18n_service` parameter yet (https://github.com/edx/xblock-utils/blob/v1.0.3/xblockutils/resources.py#L49).
Check if you can upgrade the xblockutils to at least v1.1.0, which introduced this parameter (https://github.com/edx/xblock-utils/blob/v1.1.0/xblockutils/resources.py#L50), and run some tests.

**Comment by xitij2000** [comment]
@umarmughal824 I'd really suggest you run the tests locally in a clean virtualenv and make sure they are working. The fact that the CircleCI test is linked to this PR means it is working with the correct commit. 

I have run the tests locally and they are still failing due to the issue @giovannicimolin pointed out above.

**Comment by xitij2000** [comment]
@umarmughal824  I noticed you asked about testing it locally. You can find the steps Circle CI uses in the circle.yml file.

**Comment by giovannicimolin** [comment]
@umarmughal824 The tests failed again. 

First, make sure they run on your local machine following the instructions from here: https://github.com/open-craft/problem-builder/tree/problem-builder-v2#running-tests and make sure your python environment has the correct requirements. 

Also, as @xitij2000 said, you can check `circleci.yml` to see step by step how the CI sets up the testing environment and runs them.

**Comment by umarmughal824** [comment]
@giovannicimolin Yeah but now the previous failure is fixed now the failure is different. I have seen ```circle.yml```.

**Comment by umarmughal824** [comment]
@giovannicimolin or @xitij2000 Can you please run these CircleCI tests now?

**Comment by umarmughal824** [comment]
@giovannicimolin or @xitij2000 Can you please run these CircleCI tests now?

File: problem_builder/tests/unit/test_problem_builder.py [hunk 1]
```diff
@@ -236,8 +236,16 @@ def test_get_option(self):
...
+        random_key, random_value = random(), random()
         self.block.get_xblock_settings = Mock(return_value={})
         with patch.object(self.block, 'get_option') as patched_get_option:
+            self.runtime_mock.service.return_value = {
+                random_key: random_value,
+                random_key: random_value,
+                random_key: random_value,
+                random_key: random_value,
+                random_key: random_value,
+            }
```
Comment (xitij2000) [inline problem_builder/tests/unit/test_problem_builder.py]: Why repeat this 5 times it has to affect. Please clean up.

Comment (umarmughal824) [reply problem_builder/tests/unit/test_problem_builder.py]: because it is expceting 5 key value pairs. that's why added it 5 times.

Comment (umarmughal824) [reply problem_builder/tests/unit/test_problem_builder.py]: Let me test if it passes the tests with single parameter. If that happens, I will keep only one.

**Comment by umarmughal824** [comment]
@xitij2000 its updated. Now you can run the tests.

File: problem_builder/tests/unit/test_problem_builder.py (hunk 1 above)
Comment (giovannicimolin) [reply problem_builder/tests/unit/test_problem_builder.py]: @umarmughal824 I believe the tests will fail because of @xitij2000 's comment. 
But you can use something like this for generating a random dict: 
```
{random.random(): random.random() for k in range(5)}
```

**Comment by giovannicimolin** [comment]
@umarmughal824 The tests ran successfully. 

Can you remove `geckodriver.log` from this PR?

**Comment by umarmughal824** [comment]
@giovannicimolin done.

**Comment by giovannicimolin** [comment]
@umarmughal824 Everything is working now and the xblock is back working. Just for double checking, I'll wait for a :+1: from @xitij2000.

**Comment by giovannicimolin** [comment]
@umarmughal824 I'll need to test the xblock now, just to check if the translations are working correctly. 
Can you provide instructions for checking if the translations are working?

**Comment by umarmughal824** [comment]
> @umarmughal824 I'll need to test the xblock now, just to check if the translations are working correctly.
> Can you provide instructions for checking if the translations are working?

You can install it in devstack and see the course having step-builder example. You will get it.
See that link https://imgur.com/a/lhOWSvm.

**Comment by giovannicimolin** [comment]
@umarmughal824 I've installed this branch (7f58e55) and the translations are not working for any language. (screenshot: https://imgur.com/a/pMjf55u)

**Comment by umarmughal824** [comment]
@giovannicimolin I have installed this branch **umarmughal824:umar/fix-circleci-test** and it's working in my case. Here is the screenshots https://imgur.com/a/cfLRoI6.

**Comment by xitij2000** [comment]
@umarmughal824 Unfortunately the translations aren't working for me either.

**Comment by giovannicimolin** [comment]
I've followed this steps to install on my devstack:
1. Cloned `problem-builder-v2` into `src/`, added your repo as a origin and checked out 7f58e55
2. Ran a `hawthorne.1` devstack
3. `make lms-shell`
4. `pip install /edx/src/problem-builder`
5. `make studio-shell`
6. `pip install /edx/src/problem-builder`
8. Added `problem-builder` and `step-builder` to course advanced modules
9. Created a new subsection, and added the xblock to it
10. Set up a few exercises with the feedback/revew page
11. Logged in as a student answered the questions and got ot the feeback page
12. Changed language by going to `http://edx.devstack.lms:18000/update_lang/`

When I changed the language, the entire page except for the xblock updated.
Try testing this branch on a clean devstack to see if you can get the same results.

**Comment by umarmughal824** [comment]
@giovannicimolin Instead of checkout this specific commit, you should pull the entire PR code then run the tests again. I guess, In that case it is not getting the entire translation code but only get the specifc specific.

**Comment by xitij2000** [comment]
@umarmughal824 I'm not sure what you mean? The commit he mentioned is the latest commit in this PR so it includes all the other changes.

**Comment by umarmughal824** [comment]
@giovannicimolin I guess you should follow this link.
https://help.github.com/articles/checking-out-pull-requests-locally/

**Comment by giovannicimolin** [comment]
@umarmughal824 This is my `git log`:
```
7f58e55 (HEAD -> umar/fix-circleci-test, umar/umar/fix-circleci-test) remove geckodriver.log file
1bfee33 (origin/umarmughal824-umar/fix-circleci-test) remove unnecessary lines
900dee4 fix circleCI error 'Mock' object is not iterable
a0b95b9 fix circleCI tests to get the latest version of xblock-utils
24f640d (origin/giovanni/test-circleci-tests) fix circleci test
43dbabd (umar/problem-builder-v2) fix merge conflict
5947797 (origin/problem-builder-v2, problem-builder-v2) Fix missing translations, add underscore js translations and version bump (#219)
b92cced fixed missing translation, add undersocre js translations and version bump
...
```

**Comment by umarmughal824** [comment]
@giovannicimolin check it now.

**Comment by umarmughal824** [comment]
@giovannicimolin @xitij2000 please mention the strings which are not working with the screenshots.

**Comment by giovannicimolin** [comment]
@umarmughal824 The strings not translated are, basically all of the xblock:
- You scored 0% on this assessment.
- You answered 1 questions correctly.
- You answered 1 questions partially correctly.
- You answered 1 questions incorrectly.
- Try again button
- You might consider reviewing the following...

**Comment by umarmughal824** [comment]
@giovannicimolin This is what you got before my last change. So have you tried after the last commit?

When are you getting these strings not translated on Submission?

Please try a few things
1) on submission (are translations working here?)
2) after submission clear the cache and refresh the page  (are translations working here?)

Please check these two things and let me know what are experienceing.

and Please send the screenshots as well for both above mentioned scenarios.

**Comment by giovannicimolin** [comment]
@umarmughal824 I've pulled your last commit, uninstalled `xblock-problem-builder` and installed it again.I've also ran `make lms-static` and `make studio-static` to make sure I didn't get any issues.

The translations are still **not** working, and I've tested the xblock on both Chrome and Firefox.

Screenshot: https://imgur.com/a/gblv7Vy

**Comment by umarmughal824** [comment]
@giovannicimolin in your edxapp environment run this command ```pip list``` and see the **problem-builder** where it is refering. See in my case it is refering to ```edx/src/problem-builder``` which is the exact location in my case.

https://imgur.com/a/H1pfLvV

**Comment by umarmughal824** [comment]
@giovannicimolin I have checked at same place where you are checking it. It's working here. See https://imgur.com/a/VPwCVDd.

You will have to do following steps
- Visit http://lms.mcka.local/update_lang/ 
- Change your language to ar (Arabic) etc and save it.
Then visit the course. You will get the translations.

**Comment by umarmughal824** [comment]
> @giovannicimolin I have checked at same place where you are checking it. It's working here. See https://imgur.com/a/VPwCVDd.
> 
> You will have to do following steps
> 
> * Visit http://lms.mcka.local/update_lang/
> * Change your language to ar (Arabic) etc and save it.
>   Then visit the course. You will get the translations.

Have you tried my this suggetsed procedure?

**Comment by xitij2000** [comment]
@umarmughal824 You can see the exact steps that @giovannicimolin took in a comment he posted above: https://github.com/open-craft/problem-builder/pull/221#issuecomment-446973679

Have you tested this in the hawthorn/maste devstack?

**Comment by umarmughal824** [comment]
@xitij2000 / @giovannicimolin  In these steps I found one things missing after installing xblock. I am following these steps

- stop the lms
- export NO_PREREQ_INSTALL=1   (TO AVOID REINSTALLING ANY NEW REQUIREMENTS)
- run the lms again to clear the cahche.

If you don't follow these stpes you cache will remain intact and you wouldn't be able to see the translations. **All these steps are for solutions devstack**.

After that you can verify you problem-builder origin by running this command.
 **pip list** and search you xblock. It would give you the location of your mounted folder to verify that you are using the expected xblock.

In my case on running **pip list** I am getting this **xblock-problem-builder (2.12, /edx/src/problem-builder)
** which the expcted value. But in other case you are using solution custom requirements then it would be something like this **xblock-ooyala-player (2.0.20, /edx/app/edxapp/venvs/edxapp/src/xblock-ooyala)**.

**Comment by xitij2000** [comment]
@umarmughal824 We generally test on the docker devstack since its faster. The steps you are mentioning are the standard steps we follow. I will have a look again a while. Till then I would recommend that you try running the block on the main edx-platform docker devstack.

**Comment by umarmughal824** [comment]
@xitij2000 sure. Please try it on your side. I am going to verfiy it on other machine.

**Comment by umarmughal824** [comment]
@xitij2000 @giovannicimolin I tested it on another machine. It's working.

**Comment by xitij2000** [comment]
@umarmughal824 Just to be clear, did you try this on a clean Docker-based devstack running hawthorn.1 or later?

Even with all the latest changes I am getting inconsistent results:
screenshot_2018-12-17 unit susssection l pb your platform name here

The above is only affecting Arabic as far as I can tell. 

Additionally the i18n_service doesn't seem to be getting passed correctly here: https://github.com/open-craft/problem-builder/pull/221/files#diff-40bbbff3ad6e6283b732f218aaa286ffL292

In order to avoid so many review cycles in the future I'd advise you thoroughly test the cahnges made to the block on the latest devstack (not just the solutions devstack), and run the tests locally. Since this is touching almost every part of the block you should ideally run the full test suite locally.

**Comment by xitij2000** [comment]
@umarmughal824 I assume it worked now because you fixed it in the meantime? I am not sure what you are asking. The steps are the same, roughly:
1. Install xblock
2. Restart lms
3. Change langauge
4. Test

**Comment by umarmughal824** [comment]
@xitij2000 All of the strings are working for my case. Please can you re-confirm?

For apros on submission we are unable to see the translations which I am currently working on. Mapping of languages.

**Comment by umarmughal824** [comment]
I have no tested it on Hawthorn or master devstack. I tested it on only solutions devstack. Do you want me to test it on Hawthorn too?

**Comment by giovannicimolin** [comment]
@umarmughal824 Yes, please do that and ping us when you are done and the translations are working.

**Comment by giovannicimolin** [comment]
@umarmughal824 The translations seem to be working now. I've checked for all translations that you added on the other PR.

I found an issue with `ja-jp` language: the number of correct/incorrect/partially correct never changes on feedback. 
Screenshots of the same page with different language:
ja-jp
pt

**Comment by umarmughal824** [comment]
@giovannicimolin @xitij2000 counter part is fixed too. please have a look.

**Comment by xitij2000** [comment]
@umarmughal824 I pointed out in a previous comment that the i18_service is not being passed correctly here: https://github.com/open-craft/problem-builder/pull/221/files#diff-40bbbff3ad6e6283b732f218aaa286ffR292
That is still not addressed. Please address all the comments and issues from the previous review before asking for an additional review.

**Comment by umarmughal824** [comment]
@xitij2000 is passing correctly. I have checked it.

**Comment by umarmughal824** [comment]
@giovannicimolin @xitij2000 I don't know why are you comparing it with me ooyala. It has no relation with it. We customized it only for ooyala but the noraml procedure to pass it as a context.

**Comment by umarmughal824** [comment]
@giovannicimolin @xitij2000 please check it now. It has been fixed.

thanks a lot guys.

**Comment by giovannicimolin** [comment]
Looks good to me now! :smile: 
Let's just wait for a :+1: from @xitij2000 too, since this PR had quite a bit of feedback.

:+1: 

- [x] I tested this:
1.  Installed xblock, created demo problem
2. Solved the problem as user
3. Checked feedback strings (including plurals) on these languages:
```
ar
fr
es-419
de-de
ja-jp
zh-cn
pt-br
```
- [x] I've read through the code

**Comment by umarmughal824** [comment]
thanks @giovannicimolin, sure we should wait for his review.

**Comment by umarmughal824** [comment]
@giovannicimolin I have updated translations for master branch as well. Will you please have a lool on it too on another PR?

**Comment by umarmughal824** [comment]
@kshitij will you please review it? You review is required. @giovannicimolin have already approved it.

**Comment by xitij2000** [comment]
@umarmughal824 I have merged this. @giovannicimolin's review is sufficient. 

Could you please update the description to properly mention all the changes introduced by this PR.

**Comment by umarmughal824** [comment]
@xitij2000 I have updated the description.
@xitij2000 Will you please create a release tag for it?
thanks

**Comment by xitij2000** [comment]
@umarmughal824 
I have created a release tag. 

Note that the fix isn't for Circle CI, it has nothing to do with Circle CI. The tests would fail if you run them locally as well. The fixes are for bugs introduced in PR 219 that was not only causing the tests to fail, but also would cause the block to crash the site. 

It's important to be precise in case anyone is using the problem-builder-v2 branch or looking at why a commit has failed tests. I have updated the desription to reflect that.
